- Total User 
  Users =
DISTINCTCOUNT(users[user_id])

- Total Revenue
  Revenue =
SUM(purchases[revenue])

- Total purchases
  Purchases =
COUNT(purchases[purchase_id])

- ARPU
  ARPU =
DIVIDE(
[Revenue],
[Users]
)

- ARPPU
  ARPPU =
DIVIDE(
[Revenue],
DISTINCTCOUNT(purchases[user_id])
)

- Revenue Trend
  Revenue Trend =
SUM(purchases[revenue])
